version: '3'
services:
  db:
    image: mariadb
    expose:
      - "3306"
    environment:
      - MYSQL_DATABASE=webservice
      - MYSQL_ROOT_PASSWORD=root
    volumes:
        - ./db/webservice.sql:/docker-entrypoint-initdb.d/webservice.sql
  app:
    build: .
    volumes:
      - .:/code
    ports:
        - "0.0.0.0:8000:8000"
  nginx:
    image: nginx
    volumes:
        - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
        - "0.0.0.0:80:80"
