version: '3'
services:
  db:
    image: mysql:5.7
    restart: always
    expose:
      - "3306"
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=webservice
      - MYSQL_ROOT_PASSWORD=root
    command: "mysql -uroot -proot webservice < ./db/webservice.sql"
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - .:/code
    ports:
      - "8080:8080"
    depends_on:
      - db

