# Generated by Django 2.0.4 on 2018-04-26 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('type', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='AttrValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=256)),
                ('attr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.Attr')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='FileObj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_system', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='file_system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.FileObj'),
        ),
        migrations.AddField(
            model_name='attrvalue',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.File'),
        ),
        migrations.AddField(
            model_name='attr',
            name='obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.FileObj'),
        ),
    ]
