# Generated by Django 2.0.4 on 2018-08-17 10:37

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import rest.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('type_attr', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='AttrValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=256)),
                ('attr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.Attr')),
            ],
        ),
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('store_path', models.CharField(max_length=1024)),
                ('host', models.CharField(help_text='IP and port server storage', max_length=256)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('type_file', models.CharField(max_length=20)),
                ('path', models.CharField(max_length=1024)),
                ('backup', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='rest.Backup')),
            ],
        ),
        migrations.CreateModel(
            name='FileData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_id', models.IntegerField(default=0)),
                ('checksum', models.CharField(max_length=256)),
                ('block_data', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/home/locvu/backup/'), upload_to=rest.models.key_store_upload_to)),
                ('file_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.File')),
            ],
        ),
        migrations.CreateModel(
            name='FileSys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_system', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='KeyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='Qj3lfEV2NJ3aJQYIbglBvfT4VrWSdt5zmxi3E4KPmrI=', max_length=44)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='file_system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.FileSys'),
        ),
        migrations.AddField(
            model_name='attrvalue',
            name='file_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.File'),
        ),
        migrations.AddField(
            model_name='attr',
            name='file_sys',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.FileSys'),
        ),
    ]
