# Generated by Django 2.0.4 on 2018-05-08 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_data', models.FileField(upload_to='')),
                ('block_id', models.IntegerField(default=0)),
                ('checksum', models.CharField(max_length=256)),
                ('file_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.File')),
            ],
        ),
    ]
