#!/home/locvu/djangows/env/bin/python
import os
from list import main
import argparse

parser = argparse.ArgumentParser(description="Run the list backups")
parser.add_argument('-c', '--config-file', dest='config_file', default='conf.d/client.conf',
                    help='Path of config file')
parser.add_argument('-p', '--pk', dest='pk', help='Index of backup')
parser.add_argument('-t', '--target', dest='repo_target', help='Path to file restore')
args = parser.parse_args()


if os.path.exists(args.config_file):
    pass
else:
    print("File config does not exist ")
    exit(1)


if args.repo_target and args.repo_target.endswith('/'):
    args.repo_target = args.repo_target[:len(args.repo_target)-1]
main(args)
