#!/home/locvu/djangows/env/bin/python  
import os
from restore import main
import argparse


parser = argparse.ArgumentParser(description="Run the Backup CLI")
parser.add_argument('-c', '--config-file', dest='config_file', default='conf.d/client.conf',
                    help='Path of config file')
parser.add_argument('-t', '--target', dest='repo_target',
                    help='Path of directory need to backup')
parser.add_argument('-s', '--server', dest='server_address',
                    help='Server backup')
parser.add_argument('-p', '--pk', dest='backup_id', required=True,
                    help='Primary key need to backup')
parser.add_argument('-j', dest='job_id', default=None,
                    help='Job in controller')                                
args = parser.parse_args()


# check file config
if os.path.exists(args.config_file):
    pass
else: 
    print("File config does not exist ")
    exit(1)


# check type pk is `number`
try:
    val = int(args.backup_id)
except ValueError:
    print("PK's not an int!") 
    exit(1)
    

if args.repo_target and args.repo_target.endswith('/'):
    args.repo_target = args.repo_target[:len(args.repo_target)-1]
main(args)
